name: nn-and-nlp
channels:
  - pytorch
  - defaults
dependencies:
  - numpy~=1.21.2
  - python~=3.9.7
  - pytorch~=1.11.0
  - torchaudio~=0.11.0
  - torchvision~=0.12.0
  - matplotlib~=3.5.1
  - tqdm
  - scipy~=1.7.3
  - pandas~=1.4.1
  - ipykernel
  - pip:
    - gdown
    - httpimport
